Use named arguments when calling `record_batch` during no-target inference (#1680)
There is a mismatch in the signature of `record_batch` on the
`RegionalIndexAggregator`:
https://github.com/ai2cm/full-model/blob/60418f9aef0fed8648a0209e768cfb9bde77390b/fme/ace/aggregator/inference/enso/dynamic_index.py#L86
and other time-dependent aggregators used in no-target inference:
https://github.com/ai2cm/full-model/blob/60418f9aef0fed8648a0209e768cfb9bde77390b/fme/ace/aggregator/inference/annual.py#L166

This leads to an error when `record_batch` is used without named
arguments here:
https://github.com/ai2cm/full-model/blob/60418f9aef0fed8648a0209e768cfb9bde77390b/fme/ace/aggregator/inference/main.py#L681

E.g. in [this
job](https://beaker.allen.ai/orgs/ai2/workspaces/ace/work/01JPAGQ4YPN1EYG9Y2TBX97QH3?taskId=01JPAGQ4Z4Q3XFCXCAYQYMT0N3&jobId=01JPAGQ52TK2DX2G4K8F3H1NX7),
which precipitated this traceback:

```
2025-03-14T14:27:59.409Z Traceback (most recent call last):
2025-03-14T14:27:59.409Z   File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
2025-03-14T14:27:59.409Z     return _run_code(code, main_globals, None,
2025-03-14T14:27:59.409Z   File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
2025-03-14T14:27:59.409Z     exec(code, run_globals)
2025-03-14T14:27:59.409Z   File "/usr/local/lib/python3.10/dist-packages/fme/ace/inference/__main__.py", line 15, in <module>
2025-03-14T14:27:59.409Z     main(args.yaml_config, segments=args.segments, override_dotlist=args.override)
2025-03-14T14:27:59.410Z   File "/usr/local/lib/python3.10/dist-packages/fme/ace/inference/inference.py", line 217, in main
2025-03-14T14:27:59.410Z     return run_inference_from_config(config)
2025-03-14T14:27:59.410Z   File "/usr/local/lib/python3.10/dist-packages/fme/ace/inference/inference.py", line 279, in run_inference_from_config
2025-03-14T14:27:59.410Z     run_inference(
2025-03-14T14:27:59.410Z   File "/usr/local/lib/python3.10/dist-packages/fme/core/generics/inference.py", line 132, in run_inference
2025-03-14T14:27:59.410Z     logs = aggregator.record_batch(
2025-03-14T14:27:59.410Z   File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
2025-03-14T14:27:59.410Z     return func(*args, **kwargs)
2025-03-14T14:27:59.410Z   File "/usr/local/lib/python3.10/dist-packages/fme/ace/aggregator/inference/main.py", line 666, in record_batch
2025-03-14T14:27:59.410Z     self._aggregators[name].record_batch(data.time, data.prediction)
2025-03-14T14:27:59.410Z   File "/usr/local/lib/python3.10/dist-packages/fme/ace/aggregator/inference/enso/dynamic_index.py", line 110, in record_batch
2025-03-14T14:27:59.410Z     if self._calendar is None and time.dt.calendar is not None:
2025-03-14T14:27:59.411Z AttributeError: 'dict' object has no attribute 'dt'
```

To be safer, this PR updates the code to use named arguments, which
fixes this bug. We also switch the order of the arguments in the
`RegionalIndexAggregator` to be consistent.

Changes:
- Switches to using named arguments when calling `record_batch` on
time-dependent aggregators during no-target inference.
- Switches the signature of `RegionalIndexAggregator.record_batch` to be
consistent with the signature of other aggregators.

- [x] Tests added (it turns out I could modify an existing test in such
a way that it would have caught this issue earlier).