Fix data processing error when there is no land vertical coordinate (#1744)
This PR fixes a minor issue introduced in #1679. In datasets where we do
vertically coarsen any land fields, like SHiELD datasets, we do not have
a land vertical coordinate to drop, so we encounter the following error:
```
Traceback (most recent call last):
  File "//script.py", line 892, in <module>
    main()
  File "/usr/local/lib/python3.12/site-packages/click/core.py", line 1161, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/click/core.py", line 1082, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/click/core.py", line 1443, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/click/core.py", line 788, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "//script.py", line 861, in main
    ds = ds.drop_vars(standard_names.dropped_variables)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/xarray/core/dataset.py", line 6118, in drop_vars
    self._assert_all_in_dataset(names_set)
  File "/usr/local/lib/python3.12/site-packages/xarray/core/dataset.py", line 5982, in _assert_all_in_dataset
    raise ValueError(
ValueError: These variables cannot be found in this dataset: ['zfull_soil']
```
A simple fix is to only specify this as a dropped variable if vertically
resolved land fields exist.

Changes:
- Only specify that we would like to drop the land vertical coordinate
when vertically resolved land fields exist.
- Slightly simplify the logic for defining dropped land variables by
using `self.vertically_resolved_names_land` instead of
`self.land_names_to_vertically_coarsen_by_height_weighting +
self.land_names_to_vertically_coarsen_by_sum`.

This argo job is running smoothly with these changes:
`compute-fme-dataset-ensemble-l9frr`.