Include wandb in mypy environment (#1632)
This PR resolves a long-standing local issue some people have (including
me) where mypy gives a large number of errors on wandb:

```
mypy.....................................................................Failed
- hook id: mypy
- exit code: 1

fme/core/wandb.py:20: error: Name "wandb.Histogram" is not defined  [name-defined]
fme/core/wandb.py:35: error: Module has no attribute "Histogram"  [attr-defined]
fme/core/wandb.py:36: error: Module has no attribute "Histogram"  [attr-defined]
(...)
Found 18 errors in 1 file (checked 339 source files)
```

Normally I only get these errors when running with `--all-files` as the
wandb file doesn't get checked otherwise, but I have started getting
this issue on commit as well, requiring I commit with `--no-verify`
(which is not ideal).

Changes:
- Include wandb in mypy pre-commit environment

- [ ] Tests added

---------

Co-authored-by: Oliver Watt-Meyer <oliverwatt@gmail.com>